# Generated by Django 6.1.1 on 2026-10-01 01:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quality_area',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('codigo_plano', models.CharField(blank=True, max_length=150, null=True)),
                ('articulo', models.CharField(max_length=250)),
                ('cantidad_a_inspeccionar', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unidades_liberadas', models.PositiveIntegerField(default=0)),
                ('resultado_actual', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('concesion', 'Concesión')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quality_itemsdi',
            },
        ),
        migrations.CreateModel(
            name='InspeccionSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inspeccion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_inspeccionada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('resultado', models.CharField(choices=[('en_proceso', 'En proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('concesion', 'Concesión')], default='en_proceso', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='quality.itemsdi')),
            ],
            options={
                'db_table': 'quality_inspeccionsdi',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('archivo', models.FileField(upload_to='evidencias_sdi/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_sdi_subidas', to=settings.AUTH_USER_MODEL)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='quality.inspeccionsdi')),
            ],
            options={
                'db_table': 'quality_evidenciasdi',
            },
        ),
        migrations.CreateModel(
            name='ConcesionSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='solicitada', max_length=20)),
                ('responsable_ingenieria', models.CharField(max_length=150)),
                ('justificacion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='concesiones_sdi/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concesiones_sdi_registradas', to=settings.AUTH_USER_MODEL)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concesiones', to='quality.inspeccionsdi')),
            ],
            options={
                'db_table': 'quality_concesionsdi',
            },
        ),
        migrations.CreateModel(
            name='InspeccionVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebarbas', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('no_aplica', 'No aplica')], max_length=20)),
                ('rayaduras', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('no_aplica', 'No aplica')], max_length=20)),
                ('golpes', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('no_aplica', 'No aplica')], max_length=20)),
                ('deformidad', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('no_aplica', 'No aplica')], max_length=20)),
                ('pintura', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('no_aplica', 'No aplica')], max_length=20)),
                ('burbujas', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('no_aplica', 'No aplica')], max_length=20)),
                ('planitud', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('no_aplica', 'No aplica')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('inspeccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion_visual', to='quality.inspeccionsdi')),
            ],
            options={
                'db_table': 'quality_inspeccionvisual',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('jefe_calidad', 'Jefe de Calidad'), ('inspector', 'Inspector')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='quality.area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_perfilusuario',
            },
        ),
        migrations.CreateModel(
            name='RechazoSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('estetico', 'Defecto estético'), ('fuera_tolerancia', 'Fuera de tolerancia'), ('producto_no_disponible', 'Producto no disponible'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('cantidad_afectada', models.PositiveIntegerField(blank=True, null=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos', to='quality.inspeccionsdi')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechazos_sdi_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_rechazosdi',
            },
        ),
        migrations.CreateModel(
            name='SDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo_bod', models.BooleanField(default=False)),
                ('activacion_proyecto', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='El código de proyecto debe contener entre 1 y 6 dígitos.', regex='^\\d{1,6}$')])),
                ('numero_sdi', models.TextField(validators=[django.core.validators.RegexValidator(message='El número de SDI debe contener solamente dígitos.', regex='^\\d+$')])),
                ('fecha_emision', models.DateField()),
                ('proyecto', models.CharField(max_length=200)),
                ('departamento_solicitante', models.CharField(max_length=150)),
                ('solicitante', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('concesion', 'Concesión'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdi_creadas', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sdi_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_sdi',
            },
        ),
        migrations.AddField(
            model_name='itemsdi',
            name='sdi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.sdi'),
        ),
        migrations.CreateModel(
            name='HistorialSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=150)),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_sdi', to=settings.AUTH_USER_MODEL)),
                ('inspeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='quality.inspeccionsdi')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='quality.itemsdi')),
                ('sdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='quality.sdi')),
            ],
            options={
                'db_table': 'quality_historialsdi',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='inspeccionsdi',
            index=models.Index(fields=['inspector', 'resultado'], name='idx_insp_usuario_result'),
        ),
        migrations.AddConstraint(
            model_name='inspeccionsdi',
            constraint=models.UniqueConstraint(fields=('item', 'numero_inspeccion'), name='uq_item_numero_inspeccion'),
        ),
        migrations.AddConstraint(
            model_name='inspeccionsdi',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_inspeccionada__gt', 0)), name='ck_inspeccion_cantidad'),
        ),
        migrations.AddConstraint(
            model_name='rechazosdi',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_afectada__isnull', True), ('cantidad_afectada__gt', 0), _connector='OR'), name='ck_rechazo_cantidad'),
        ),
        migrations.AddIndex(
            model_name='sdi',
            index=models.Index(fields=['estado'], name='idx_sdi_estado'),
        ),
        migrations.AddIndex(
            model_name='sdi',
            index=models.Index(fields=['inspector', 'estado'], name='idx_sdi_insp_estado'),
        ),
        migrations.AddIndex(
            model_name='sdi',
            index=models.Index(fields=['fecha_emision'], name='idx_sdi_fecha'),
        ),
        migrations.AddConstraint(
            model_name='sdi',
            constraint=models.UniqueConstraint(fields=('prefijo_bod', 'activacion_proyecto', 'numero_sdi'), name='uq_codigo_sdi'),
        ),
        migrations.AddConstraint(
            model_name='sdi',
            constraint=models.CheckConstraint(condition=models.Q(('activacion_proyecto__regex', '^\\d{1,6}$')), name='ck_sdi_proyecto_digitos'),
        ),
        migrations.AddConstraint(
            model_name='sdi',
            constraint=models.CheckConstraint(condition=models.Q(('numero_sdi__regex', '^\\d+$')), name='ck_sdi_numero_digitos'),
        ),
        migrations.AddIndex(
            model_name='itemsdi',
            index=models.Index(fields=['resultado_actual'], name='idx_item_resultado'),
        ),
        migrations.AddConstraint(
            model_name='itemsdi',
            constraint=models.UniqueConstraint(fields=('sdi', 'orden'), name='uq_sdi_orden'),
        ),
        migrations.AddConstraint(
            model_name='itemsdi',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_a_inspeccionar__gt', 0)), name='ck_item_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemsdi',
            constraint=models.CheckConstraint(condition=models.Q(('unidades_liberadas__lte', models.F('cantidad_a_inspeccionar'))), name='ck_item_unidades_liberadas'),
        ),
        migrations.AddIndex(
            model_name='historialsdi',
            index=models.Index(fields=['sdi', 'fecha'], name='idx_hist_sdi_fecha'),
        ),
    ]
