# Generated by Django 6.1.1 on 2026-10-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inspeccionsdi',
            name='uq_item_numero_inspeccion',
        ),
        migrations.RemoveConstraint(
            model_name='inspeccionsdi',
            name='ck_inspeccion_cantidad',
        ),
        migrations.RemoveIndex(
            model_name='inspeccionsdi',
            name='idx_insp_usuario_result',
        ),
        migrations.AddField(
            model_name='inspeccionsdi',
            name='cantidad_aprobada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspeccionsdi',
            name='resultado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('aprobada', 'Aprobada'), ('parcial', 'Parcial'), ('rechazada', 'Rechazada'), ('concesion', 'Concesión')], default='en_proceso', max_length=20),
        ),
        migrations.AlterModelTable(
            name='inspeccionsdi',
            table=None,
        ),
    ]
